In [1]:
import numpy as np
from numpy import linalg as LA

In [2]:
a = np.array([3, 5])
V = np.array([
    [1, 9], 
    [2, 0],
    [1, 7]
    ])

np.dot(a, V.T)

array([48,  6, 38])

In [3]:
V / LA.norm(V, axis=1, keepdims=True)

array([[0.11043153, 0.99388373],
       [1.        , 0.        ],
       [0.14142136, 0.98994949]])

In [4]:
def closest_to_antigrad(grad, vectors): 
    sim = np.dot(grad, vectors.T)
    return sim.argmin()


In [5]:
closest_to_antigrad(a, V)

np.int64(1)

In [6]:
A = np.array([
    [2, 2, -2],
    [5, 1, -3],
    [1, 5, -3]
])

In [7]:
np.mean(A, axis=0) 

array([ 2.66666667,  2.66666667, -2.66666667])

In [8]:
np.std(A, axis=0).astype(int)

array([1, 1, 0])

In [9]:
A_normed = ((A - np.mean(A, axis=0)) / np.std(A, axis=0)).astype(int)

In [10]:
A_normed

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [11]:
A[0, :A.shape[1]]

array([ 2,  2, -2])

In [12]:
np.allclose([0, 0, 0], 0)

True

In [13]:
A[0, :].argmax()

np.int64(0)

In [14]:
np.where(A[1] > 3)[0][-1]

np.int64(0)

In [20]:
x = np.sqrt(36) 

In [22]:
if np.isclose(x, round(x)):
    print('whole number')

whole number
