In [181]:
import numpy as np
from numpy import linalg as LA

In [182]:
a = np.array([3, 5])
V = np.array([
    [1, 9], 
    [2, 0],
    [1, 7]
    ])

np.dot(a, V.T)

array([48,  6, 38])

In [183]:
V / LA.norm(V, axis=1, keepdims=True)

array([[0.11043153, 0.99388373],
       [1.        , 0.        ],
       [0.14142136, 0.98994949]])

In [184]:
def closest_to_antigrad(grad, vectors): 
    sim = np.dot(grad, vectors.T)
    return sim.argmin()


In [185]:
closest_to_antigrad(a, V)

np.int64(1)

In [186]:
A = np.array([
    [2, 2, -2],
    [5, 1, -3],
    [1, 5, -3]
])

In [187]:
np.mean(A, axis=0) 

array([ 2.66666667,  2.66666667, -2.66666667])

In [188]:
np.std(A, axis=0).astype(int)

array([1, 1, 0])

In [189]:
A_normed = ((A - np.mean(A, axis=0)) / np.std(A, axis=0)).astype(int)

In [190]:
A_normed

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [191]:
A[0, :A.shape[1]]

array([ 2,  2, -2])

In [192]:
np.allclose([0, 0, 0], 0)

True

In [193]:
A[0, :].argmax()

np.int64(0)

In [194]:
np.where(A[1] > 3)[0][-1]

np.int64(0)

In [195]:
x = np.sqrt(36) 

In [196]:
if np.isclose(x, round(x)):
    print('whole number')

whole number


In [197]:
A

array([[ 2,  2, -2],
       [ 5,  1, -3],
       [ 1,  5, -3]])

In [198]:
indices = np.arange(A.shape[0])

In [199]:
indices != 1

array([ True, False,  True])

In [200]:
A[np.ix_(indices != 1, indices != 0)]

array([[ 2, -2],
       [ 5, -3]])

In [201]:
np.roots([1, 2, 1]).dtype not in [int, float]

False

In [202]:
a = np.array([-1, 2, -4])

In [203]:
np.sort(a)

array([-4, -1,  2])

In [ ]:
a1, p, q, r, s, t, u = map(int, input().split())
a = a1
b = -(t*q + r*p)
c = r*u*q + p*s*t - a1*s*u

all_x = np.roots([a, b, c])

if not np.allclose(all_x, all_x.round(), atol=1e-4):
    print('NO_ROOTS')
else:
    print(*np.sort(all_x.round().astype(int)), sep=' ')

1 -2 1
[1.00000001 0.99999999]
1 1


In [205]:
all_x

array([1.00000001, 0.99999999])