In [1]:
import numpy as np
from numpy import linalg as LA

In [14]:
a = np.array([3, 5])
V = np.array([
    [1, 9], 
    [2, 0],
    [1, 7]
    ])

np.dot(a, V.T)

array([48,  6, 38])

In [23]:
V / LA.norm(V, axis=1, keepdims=True)

array([[0.11043153, 0.99388373],
       [1.        , 0.        ],
       [0.14142136, 0.98994949]])

In [15]:
def closest_to_antigrad(grad, vectors): 
    sim = np.dot(grad, vectors.T)
    return sim.argmin()


In [16]:
closest_to_antigrad(a, V)

np.int64(1)

In [ ]:
 % 1 == 0

True

In [19]:
A = np.array([
    [2, 2, -2],
    [5, 1, -3],
    [1, 5, -3]
])

In [23]:
np.mean(A, axis=0) 

array([ 2.66666667,  2.66666667, -2.66666667])

In [22]:
np.std(A, axis=0).astype(int)

array([1, 1, 0])

In [ ]:
A_normed = ((A - np.mean(A, axis=0)) / np.std(A, axis=0)).astype(int)

/var/folders/3s/q58jyd3x2_vbrvv36msymj600000gn/T/ipykernel_26044/3157054979.py:1: RuntimeWarning: divide by zero encountered in divide
  A_normed = (A - np.mean(A, axis=0)) / np.std(A, axis=0).astype(int)


In [21]:
A_normed

array([[-0.66666667, -0.66666667,         inf],
       [ 2.33333333, -1.66666667,        -inf],
       [-1.66666667,  2.33333333,        -inf]])