In [49]:
import numpy as np
from numpy import linalg as LA

In [50]:
a = np.array([3, 5])
V = np.array([
    [1, 9], 
    [2, 0],
    [1, 7]
    ])

np.dot(a, V.T)

array([48,  6, 38])

In [51]:
V / LA.norm(V, axis=1, keepdims=True)

array([[0.11043153, 0.99388373],
       [1.        , 0.        ],
       [0.14142136, 0.98994949]])

In [52]:
def closest_to_antigrad(grad, vectors): 
    sim = np.dot(grad, vectors.T)
    return sim.argmin()


In [53]:
closest_to_antigrad(a, V)

np.int64(1)

In [54]:
A = np.array([
    [2, 2, -2],
    [5, 1, -3],
    [1, 5, -3]
])

In [55]:
np.mean(A, axis=0) 

array([ 2.66666667,  2.66666667, -2.66666667])

In [56]:
np.std(A, axis=0).astype(int)

array([1, 1, 0])

In [57]:
A_normed = ((A - np.mean(A, axis=0)) / np.std(A, axis=0)).astype(int)

In [58]:
A_normed

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [59]:
A[0, :A.shape[1]]

array([ 2,  2, -2])

In [60]:
np.allclose([0, 0, 0], 0)

True

In [61]:
A[0, :].argmax()

np.int64(0)

In [62]:
np.where(A[1] > 3)[0][-1]

np.int64(0)

In [63]:
x = np.sqrt(36) 

In [64]:
if np.isclose(x, round(x)):
    print('whole number')

whole number


In [65]:
A

array([[ 2,  2, -2],
       [ 5,  1, -3],
       [ 1,  5, -3]])

In [66]:
indices = np.arange(A.shape[0])

In [67]:
indices != 1

array([ True, False,  True])

In [68]:
A[np.ix_(indices != 1, indices != 0)]

array([[ 2, -2],
       [ 5, -3]])

In [69]:
np.roots([1, 2, 1]).dtype not in [int, float]

False

In [70]:
a = np.array([-1, 2, -4])

In [71]:
np.sort(a)

array([-4, -1,  2])

In [72]:
A = np.array([[0, 3], [-3, 2]])

In [73]:
A.T

array([[ 0, -3],
       [ 3,  2]])

In [77]:
A - A.mean(axis=0)

array([[ 1.5,  0.5],
       [-1.5, -0.5]])

In [78]:
5 * np.eye(4, 4)

array([[5., 0., 0., 0.],
       [0., 5., 0., 0.],
       [0., 0., 5., 0.],
       [0., 0., 0., 5.]])

In [79]:
from sklearn.linear_model import Ridge, Lasso

In [81]:
n, d = map(int, input().split())
X = np.array([list(map(float, input().split())) for _ in range(n)])
y = np.array(list(map(float, input().split())))
a_r, a_l = map(float, input().split())

In [84]:
ridge_model = Ridge(fit_intercept=False, alpha=a_r)
lasso_model = Lasso(fit_intercept=False, alpha=a_l)

In [85]:
ridge_model.fit(X, y)
lasso_model.fit(X, y)

,"alpha alpha: float, default=1.0Constant that multiplies the L1 term, controlling regularizationstrength. `alpha` must be a non-negative float i.e. in `[0, inf)`.When `alpha = 0`, the objective is equivalent to ordinary leastsquares, solved by the :class:`LinearRegression` object. For numericalreasons, using `alpha = 0` with the `Lasso` object is not advised.Instead, you should use the :class:`LinearRegression` object.",2.0
,"fit_intercept fit_intercept: bool, default=TrueWhether to calculate the intercept for this model. If setto False, no intercept will be used in calculations(i.e. data is expected to be centered).",False
,"precompute precompute: bool or array-like of shape (n_features, n_features), default=FalseWhether to use a precomputed Gram matrix to speed upcalculations. The Gram matrix can also be passed as argument.For sparse input this option is always ``False`` to preserve sparsity.",False
,"copy_X copy_X: bool, default=TrueIf ``True``, X will be copied; else, it may be overwritten.",True
,"max_iter max_iter: int, default=1000The maximum number of iterations.",1000
,"tol tol: float, default=1e-4The tolerance for the optimization: if the updates are smaller or equal to``tol``, the optimization code checks the dual gap for optimality and continuesuntil it is smaller or equal to ``tol``, see Notes below.",0.0001
,"warm_start warm_start: bool, default=FalseWhen set to ``True``, reuse the solution of the previous call to fit asinitialization, otherwise, just erase the previous solution.See :term:`the Glossary `.",False
,"positive positive: bool, default=FalseWhen set to ``True``, forces the coefficients to be positive.",False
,"random_state random_state: int, RandomState instance, default=NoneThe seed of the pseudo random number generator that selects a randomfeature to update. Used when ``selection`` == 'random'.Pass an int for reproducible output across multiple function calls.See :term:`Glossary `.",None
,"selection selection: {'cyclic', 'random'}, default='cyclic'If set to 'random', a random coefficient is updated every iterationrather than looping over features sequentially by default. This(setting to 'random') often leads to significantly faster convergenceespecially when tol is higher than 1e-4.",'cyclic'


In [ ]:
print(*ridge_model.coef_.round(4))

0.9999999999999998 -1.9999999999999996
