In [49]:
import numpy as np
from numpy import linalg as LA

In [50]:
a = np.array([3, 5])
V = np.array([
    [1, 9], 
    [2, 0],
    [1, 7]
    ])

np.dot(a, V.T)

array([48,  6, 38])

In [51]:
V / LA.norm(V, axis=1, keepdims=True)

array([[0.11043153, 0.99388373],
       [1.        , 0.        ],
       [0.14142136, 0.98994949]])

In [52]:
def closest_to_antigrad(grad, vectors): 
    sim = np.dot(grad, vectors.T)
    return sim.argmin()


In [53]:
closest_to_antigrad(a, V)

np.int64(1)

In [54]:
A = np.array([
    [2, 2, -2],
    [5, 1, -3],
    [1, 5, -3]
])

In [55]:
np.mean(A, axis=0) 

array([ 2.66666667,  2.66666667, -2.66666667])

In [56]:
np.std(A, axis=0).astype(int)

array([1, 1, 0])

In [57]:
A_normed = ((A - np.mean(A, axis=0)) / np.std(A, axis=0)).astype(int)

In [58]:
A_normed

array([[0, 0, 1],
       [1, 0, 0],
       [0, 1, 0]])

In [59]:
A[0, :A.shape[1]]

array([ 2,  2, -2])

In [60]:
np.allclose([0, 0, 0], 0)

True

In [61]:
A[0, :].argmax()

np.int64(0)

In [62]:
np.where(A[1] > 3)[0][-1]

np.int64(0)

In [63]:
x = np.sqrt(36) 

In [64]:
if np.isclose(x, round(x)):
    print('whole number')

whole number


In [65]:
A

array([[ 2,  2, -2],
       [ 5,  1, -3],
       [ 1,  5, -3]])

In [66]:
indices = np.arange(A.shape[0])

In [67]:
indices != 1

array([ True, False,  True])

In [68]:
A[np.ix_(indices != 1, indices != 0)]

array([[ 2, -2],
       [ 5, -3]])

In [69]:
np.roots([1, 2, 1]).dtype not in [int, float]

False

In [70]:
a = np.array([-1, 2, -4])

In [71]:
np.sort(a)

array([-4, -1,  2])

In [72]:
A = np.array([[0, 3], [-3, 2]])

In [73]:
A.T

array([[ 0, -3],
       [ 3,  2]])

In [77]:
A - A.mean(axis=0)

array([[ 1.5,  0.5],
       [-1.5, -0.5]])