In [2]:
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve, inv

In [3]:
# Определяем матрицу A и правую часть b
A = np.array([[0, 1, 0],
                [1, 1, 2],
                [0, 3, 1]], dtype=float)
b = np.array([0, 14, 17], dtype=float)

# 1. Вычисляем PLU-разложение с помощью lu_factor
lu_and_piv = lu_factor(A)
print(f"Комбинированная матрица LU: \n {lu_and_piv[0]}")
print(f"Индексы перестановок: \n {lu_and_piv[1]}")

Комбинированная матрица LU: 
 [[ 1.          1.          2.        ]
 [ 0.          3.          1.        ]
 [ 0.          0.33333333 -0.33333333]]
Индексы перестановок: 
 [1 2 2]


In [4]:
# 2. Решаем систему Ax = b, используя полученную факторизацию
x = lu_solve(lu_and_piv, b)
print(f"Решение системы Ax = b: \n {x}")

Решение системы Ax = b: 
 [-20.   0.  17.]


In [5]:
# Матрицы P, L, U можно получить с помощью scipy.linalg.lu
P, L, U = lu(A)
print(f"Перестановочная матрица P: \n {P}")
print(f"Нижнетреугольная матрица L: \n {L}")
print(f"Верхнетреугольная матрица U: \n {U}")

Перестановочная матрица P: 
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
Нижнетреугольная матрица L: 
 [[1.         0.         0.        ]
 [0.         1.         0.        ]
 [0.         0.33333333 1.        ]]
Верхнетреугольная матрица U: 
 [[ 1.          1.          2.        ]
 [ 0.          3.          1.        ]
 [ 0.          0.         -0.33333333]]


In [6]:
A = np.array([
    [1, 1],
    [1, 2]
])

P, L, U = lu(A)

P, L, U

(array([[1., 0.],
        [0., 1.]]),
 array([[1., 0.],
        [1., 1.]]),
 array([[1., 1.],
        [0., 1.]]))

In [7]:
np.dot(A[1], A[1])

np.int64(5)